version: 2
jobs: 
  build:
    shell: /bin/bash --login 
    docker:
      - image: circleci/node:8.9.4
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      - CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      # Variables used in build steps
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: manifest/package.xml
    steps:
      - checkout
      - run:
          name: "Create Artifacts folder" 
          command: |
            # Create sfdx directory
            mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: "Create SFDX Folder" 
          command: |
            # Create sfdx directory
            mkdir sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            ./sfdx/install
            sfdx
      - run: 
          name: Install PMD static apex scanner
          command: sh build/PMD_installPMD.sh
      - run: 
          name: Scan /force-app folder with PMD
          command: sh build/PMD_scanSRCFolder.sh
      - run:
          name: Decrypt server key
          command: |
            #Decrypt server key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
      - run:
          name: Authorize Target Deployment Org
          command: |
            #Authorize target org
            sfdx force:auth:jwt:grant --instanceurl $ENDPOINT  --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key --username $USER_NAME --setalias UAT
      - run:
          name: Deploy to Target Deployment Org
          command: |
            #Deploy to target deployment org and run unit tests. 
            #sfdx force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
            sfdx force:source:deploy --wait 10 --manifest $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
            #Example shows how to run a check only deploy.
            #sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
      # Save test results
      - store_test_results:
        path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
        path: /tmp/circleci-artifacts
      - store_artifacts:
        path: /tmp/circleci-test-results